# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'coverage5.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Coverage(object):
    def setupUi(self, Coverage):
        Coverage.setObjectName("Coverage")
        Coverage.resize(670, 754)
        self.main_layout = QtWidgets.QWidget(Coverage)
        self.main_layout.setObjectName("main_layout")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.main_layout)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.drop_shadow_frame = QtWidgets.QFrame(self.main_layout)
        self.drop_shadow_frame.setStyleSheet("background-color: rgb(136, 138, 133);\n"
"border-radius: 10px")
        self.drop_shadow_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.drop_shadow_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.drop_shadow_frame.setObjectName("drop_shadow_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.drop_shadow_frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.drop_shadow_frame)
        self.frame_2.setStyleSheet("background-color: rgb(243, 243, 243);\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_2)
        self.stackedWidget.setObjectName("stackedWidget")
        self.datos_teoricos = QtWidgets.QWidget()
        self.datos_teoricos.setObjectName("datos_teoricos")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.datos_teoricos)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_title = QtWidgets.QLabel(self.datos_teoricos)
        self.label_title.setMinimumSize(QtCore.QSize(0, 30))
        self.label_title.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Uroob")
        font.setPointSize(20)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("\n"
"color: rgb(20, 97, 44);")
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.verticalLayout_4.addWidget(self.label_title)
        self.frame_contenido = QtWidgets.QFrame(self.datos_teoricos)
        self.frame_contenido.setMinimumSize(QtCore.QSize(0, 100))
        self.frame_contenido.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_contenido.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_contenido.setObjectName("frame_contenido")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_contenido)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_8 = QtWidgets.QFrame(self.frame_contenido)
        self.frame_8.setStyleSheet("QFrame{\n"
"    border: 5px solid rgb(255, 255, 255);\n"
"    border-radius: 15px;\n"
"    color: rgb(186, 189, 182);\n"
"}\n"
"QFrame:hover{\n"
"  border: 5px solid #f9aa33;\n"
"}")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_Datos_teoricos = QtWidgets.QLabel(self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Datos_teoricos.sizePolicy().hasHeightForWidth())
        self.label_Datos_teoricos.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Uroob")
        font.setPointSize(18)
        self.label_Datos_teoricos.setFont(font)
        self.label_Datos_teoricos.setStyleSheet("border:none;\n"
"color: rgb(20, 97, 44);")
        self.label_Datos_teoricos.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Datos_teoricos.setObjectName("label_Datos_teoricos")
        self.verticalLayout_6.addWidget(self.label_Datos_teoricos)
        self.frame_6 = QtWidgets.QFrame(self.frame_8)
        self.frame_6.setStyleSheet("border:none;")
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_redundancia = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setFamily("Uroob")
        font.setPointSize(18)
        self.label_redundancia.setFont(font)
        self.label_redundancia.setStyleSheet("color: rgb(20, 97, 44);")
        self.label_redundancia.setObjectName("label_redundancia")
        self.horizontalLayout_7.addWidget(self.label_redundancia)
        self.redundancia = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setFamily("Uroob")
        font.setPointSize(18)
        self.redundancia.setFont(font)
        self.redundancia.setStyleSheet("color: rgb(85, 87, 83);")
        self.redundancia.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.redundancia.setObjectName("redundancia")
        self.horizontalLayout_7.addWidget(self.redundancia)
        self.label_5 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setFamily("Uroob")
        font.setPointSize(18)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(85, 87, 83);\n"
"")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_7.addWidget(self.label_5)
        self.verticalLayout_6.addWidget(self.frame_6)
        self.frame_3 = QtWidgets.QFrame(self.frame_8)
        self.frame_3.setStyleSheet("border:none;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lbDistancia = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbDistancia.sizePolicy().hasHeightForWidth())
        self.lbDistancia.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Uroob")
        font.setPointSize(18)
        self.lbDistancia.setFont(font)
        self.lbDistancia.setStyleSheet("color: rgb(20, 97, 44);")
        self.lbDistancia.setObjectName("lbDistancia")
        self.horizontalLayout_5.addWidget(self.lbDistancia)
        self.distanciaTeorica = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Uroob")
        font.setPointSize(18)
        self.distanciaTeorica.setFont(font)
        self.distanciaTeorica.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.distanciaTeorica.setStyleSheet("color: rgb(85, 87, 83);")
        self.distanciaTeorica.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.distanciaTeorica.setObjectName("distanciaTeorica")
        self.horizontalLayout_5.addWidget(self.distanciaTeorica)
        self.label = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Uroob")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label.setStyleSheet("color: rgb(85, 87, 83);")
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.verticalLayout_6.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.frame_8)
        self.frame_4.setStyleSheet("border:none;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lbTiempo = QtWidgets.QLabel(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbTiempo.sizePolicy().hasHeightForWidth())
        self.lbTiempo.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Uroob")
        font.setPointSize(18)
        self.lbTiempo.setFont(font)
        self.lbTiempo.setStyleSheet("color: rgb(20, 97, 44);")
        self.lbTiempo.setObjectName("lbTiempo")
        self.horizontalLayout_6.addWidget(self.lbTiempo)
        self.tiempoTeorico = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Uroob")
        font.setPointSize(18)
        self.tiempoTeorico.setFont(font)
        self.tiempoTeorico.setStyleSheet("color: rgb(85, 87, 83);")
        self.tiempoTeorico.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tiempoTeorico.setObjectName("tiempoTeorico")
        self.horizontalLayout_6.addWidget(self.tiempoTeorico)
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Uroob")
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(85, 87, 83);")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2)
        self.verticalLayout_6.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame_8)
        self.frame_5.setStyleSheet("border:none;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_cobertura = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setFamily("Uroob")
        font.setPointSize(18)
        self.label_cobertura.setFont(font)
        self.label_cobertura.setStyleSheet("color: rgb(20, 97, 44);")
        self.label_cobertura.setObjectName("label_cobertura")
        self.horizontalLayout_4.addWidget(self.label_cobertura)
        self.cobertura = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setFamily("Uroob")
        font.setPointSize(18)
        self.cobertura.setFont(font)
        self.cobertura.setStyleSheet("color: rgb(85, 87, 83);")
        self.cobertura.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.cobertura.setObjectName("cobertura")
        self.horizontalLayout_4.addWidget(self.cobertura)
        self.unidadesCobertura = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setFamily("Uroob")
        font.setPointSize(18)
        self.unidadesCobertura.setFont(font)
        self.unidadesCobertura.setStyleSheet("color: rgb(85, 87, 83);")
        self.unidadesCobertura.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.unidadesCobertura.setObjectName("unidadesCobertura")
        self.horizontalLayout_4.addWidget(self.unidadesCobertura)
        self.verticalLayout_6.addWidget(self.frame_5)
        self.frame_11 = QtWidgets.QFrame(self.frame_8)
        self.frame_11.setStyleSheet("border:none;")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_giros = QtWidgets.QLabel(self.frame_11)
        font = QtGui.QFont()
        font.setFamily("Uroob")
        font.setPointSize(18)
        self.label_giros.setFont(font)
        self.label_giros.setStyleSheet("color: rgb(20, 97, 44);")
        self.label_giros.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_giros.setObjectName("label_giros")
        self.horizontalLayout_15.addWidget(self.label_giros)
        self.label_cantidad_giros = QtWidgets.QLabel(self.frame_11)
        font = QtGui.QFont()
        font.setFamily("Uroob")
        font.setPointSize(18)
        self.label_cantidad_giros.setFont(font)
        self.label_cantidad_giros.setStyleSheet("color: rgb(85, 87, 83);")
        self.label_cantidad_giros.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_cantidad_giros.setObjectName("label_cantidad_giros")
        self.horizontalLayout_15.addWidget(self.label_cantidad_giros)
        self.verticalLayout_6.addWidget(self.frame_11)
        self.horizontalLayout_3.addWidget(self.frame_8)
        self.frame = QtWidgets.QFrame(self.frame_contenido)
        self.frame.setEnabled(False)
        self.frame.setMaximumSize(QtCore.QSize(285, 16777215))
        self.frame.setStyleSheet("QFrame{\n"
"    border: 5px solid rgb(255, 255, 255);\n"
"    border-radius: 15px;\n"
"    color: rgb(252, 175, 62);\n"
"}\n"
"QFrame:hover{\n"
"  border: 5px solid #ffffff\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_status_simulacion = QtWidgets.QFrame(self.frame)
        self.frame_status_simulacion.setMinimumSize(QtCore.QSize(257, 50))
        self.frame_status_simulacion.setMaximumSize(QtCore.QSize(200, 50))
        self.frame_status_simulacion.setStyleSheet("QFrame{\n"
"    border: 5px solid rgb(255, 255, 255);\n"
"    \n"
"}\n"
"QFrame:hover{\n"
"  border: 5px solid #f9aa33;\n"
"}")
        self.frame_status_simulacion.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_status_simulacion.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_status_simulacion.setObjectName("frame_status_simulacion")
        self.lbStatus = QtWidgets.QLabel(self.frame_status_simulacion)
        self.lbStatus.setGeometry(QtCore.QRect(140, 10, 91, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbStatus.sizePolicy().hasHeightForWidth())
        self.lbStatus.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Uroob")
        font.setPointSize(18)
        self.lbStatus.setFont(font)
        self.lbStatus.setStyleSheet("border:none;\n"
"color: rgb(107, 142,35);")
        self.lbStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.lbStatus.setObjectName("lbStatus")
        self.lb_estado = QtWidgets.QLabel(self.frame_status_simulacion)
        self.lb_estado.setGeometry(QtCore.QRect(20, 10, 61, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_estado.sizePolicy().hasHeightForWidth())
        self.lb_estado.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Uroob")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.lb_estado.setFont(font)
        self.lb_estado.setStyleSheet("border:none;\n"
"color: rgb(20, 97, 44);")
        self.lb_estado.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_estado.setObjectName("lb_estado")
        self.verticalLayout_5.addWidget(self.frame_status_simulacion)
        self.frame_altura_simulacion = QtWidgets.QFrame(self.frame)
        self.frame_altura_simulacion.setEnabled(False)
        self.frame_altura_simulacion.setMinimumSize(QtCore.QSize(257, 50))
        self.frame_altura_simulacion.setMaximumSize(QtCore.QSize(200, 50))
        self.frame_altura_simulacion.setStyleSheet("QFrame{\n"
"    border: 5px solid rgb(255, 255, 255);\n"
"    }\n"
"QFrame:hover{\n"
"  border: 5px solid #f9aa33;\n"
"}")
        self.frame_altura_simulacion.setFrameShape(QtWidgets.QFrame.HLine)
        self.frame_altura_simulacion.setObjectName("frame_altura_simulacion")
        self.currentWayPoint = QtWidgets.QLabel(self.frame_altura_simulacion)
        self.currentWayPoint.setGeometry(QtCore.QRect(150, 10, 81, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.currentWayPoint.sizePolicy().hasHeightForWidth())
        self.currentWayPoint.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Uroob")
        font.setPointSize(18)
        self.currentWayPoint.setFont(font)
        self.currentWayPoint.setStyleSheet("border:none;\n"
"color: rgb(107, 142,35);")
        self.currentWayPoint.setFrameShape(QtWidgets.QFrame.HLine)
        self.currentWayPoint.setAlignment(QtCore.Qt.AlignCenter)
        self.currentWayPoint.setObjectName("currentWayPoint")
        self.labelWayPOint = QtWidgets.QLabel(self.frame_altura_simulacion)
        self.labelWayPOint.setGeometry(QtCore.QRect(20, 10, 81, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelWayPOint.sizePolicy().hasHeightForWidth())
        self.labelWayPOint.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Uroob")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.labelWayPOint.setFont(font)
        self.labelWayPOint.setStyleSheet("border:none;\n"
"color: rgb(20, 97, 44);")
        self.labelWayPOint.setAlignment(QtCore.Qt.AlignCenter)
        self.labelWayPOint.setObjectName("labelWayPOint")
        self.verticalLayout_5.addWidget(self.frame_altura_simulacion)
        self.frame_velocidad_simulacion_5 = QtWidgets.QFrame(self.frame)
        self.frame_velocidad_simulacion_5.setEnabled(False)
        self.frame_velocidad_simulacion_5.setMinimumSize(QtCore.QSize(257, 50))
        self.frame_velocidad_simulacion_5.setMaximumSize(QtCore.QSize(200, 50))
        self.frame_velocidad_simulacion_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_velocidad_simulacion_5.setStyleSheet("QFrame{\n"
"    border: 5px solid rgb(255, 255, 255);\n"
"    \n"
"}\n"
"QFrame:hover{\n"
"  border: 5px solid #f9aa33;\n"
"}")
        self.frame_velocidad_simulacion_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_velocidad_simulacion_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_velocidad_simulacion_5.setObjectName("frame_velocidad_simulacion_5")
        self.velocidadDrone = QtWidgets.QLabel(self.frame_velocidad_simulacion_5)
        self.velocidadDrone.setGeometry(QtCore.QRect(160, 10, 61, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.velocidadDrone.sizePolicy().hasHeightForWidth())
        self.velocidadDrone.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Uroob")
        font.setPointSize(18)
        self.velocidadDrone.setFont(font)
        self.velocidadDrone.setStyleSheet("border:none;\n"
"color: rgb(107, 142,35);")
        self.velocidadDrone.setAlignment(QtCore.Qt.AlignCenter)
        self.velocidadDrone.setObjectName("velocidadDrone")
        self.labelVeloDrone = QtWidgets.QLabel(self.frame_velocidad_simulacion_5)
        self.labelVeloDrone.setGeometry(QtCore.QRect(20, 10, 81, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelVeloDrone.sizePolicy().hasHeightForWidth())
        self.labelVeloDrone.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Uroob")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.labelVeloDrone.setFont(font)
        self.labelVeloDrone.setStyleSheet("border:none;\n"
"color: rgb(20, 97, 44);")
        self.labelVeloDrone.setAlignment(QtCore.Qt.AlignCenter)
        self.labelVeloDrone.setObjectName("labelVeloDrone")
        self.verticalLayout_5.addWidget(self.frame_velocidad_simulacion_5)
        self.frame_velocidad_simulacion_3 = QtWidgets.QFrame(self.frame)
        self.frame_velocidad_simulacion_3.setMinimumSize(QtCore.QSize(257, 50))
        self.frame_velocidad_simulacion_3.setMaximumSize(QtCore.QSize(200, 120))
        self.frame_velocidad_simulacion_3.setStyleSheet("QFrame{\n"
"    border: 5px solid rgb(255, 255, 255);\n"
"    \n"
"}\n"
"QFrame:hover{\n"
"  border: 5px solid #f9aa33;\n"
"}")
        self.frame_velocidad_simulacion_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_velocidad_simulacion_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_velocidad_simulacion_3.setObjectName("frame_velocidad_simulacion_3")
        self.TimeOfFlyDrone = QtWidgets.QLabel(self.frame_velocidad_simulacion_3)
        self.TimeOfFlyDrone.setGeometry(QtCore.QRect(160, 10, 71, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TimeOfFlyDrone.sizePolicy().hasHeightForWidth())
        self.TimeOfFlyDrone.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Uroob")
        font.setPointSize(18)
        self.TimeOfFlyDrone.setFont(font)
        self.TimeOfFlyDrone.setStyleSheet("border:none;\n"
"color: rgb(107, 142,35);")
        self.TimeOfFlyDrone.setAlignment(QtCore.Qt.AlignCenter)
        self.TimeOfFlyDrone.setObjectName("TimeOfFlyDrone")
        self.labelTiempoDrone = QtWidgets.QLabel(self.frame_velocidad_simulacion_3)
        self.labelTiempoDrone.setGeometry(QtCore.QRect(10, 10, 81, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelTiempoDrone.sizePolicy().hasHeightForWidth())
        self.labelTiempoDrone.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Uroob")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.labelTiempoDrone.setFont(font)
        self.labelTiempoDrone.setStyleSheet("border:none;\n"
"color: rgb(20, 97, 44);")
        self.labelTiempoDrone.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTiempoDrone.setObjectName("labelTiempoDrone")
        self.verticalLayout_5.addWidget(self.frame_velocidad_simulacion_3)
        self.frame_velocidad_simulacion_2 = QtWidgets.QFrame(self.frame)
        self.frame_velocidad_simulacion_2.setMinimumSize(QtCore.QSize(257, 50))
        self.frame_velocidad_simulacion_2.setMaximumSize(QtCore.QSize(200, 50))
        self.frame_velocidad_simulacion_2.setStyleSheet("QFrame{\n"
"    border: 5px solid rgb(255, 255, 255);\n"
"    \n"
"}\n"
"QFrame:hover{\n"
"  border: 5px solid #f9aa33;\n"
"}")
        self.frame_velocidad_simulacion_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_velocidad_simulacion_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_velocidad_simulacion_2.setObjectName("frame_velocidad_simulacion_2")
        self.distanciaRecorridaDrone = QtWidgets.QLabel(self.frame_velocidad_simulacion_2)
        self.distanciaRecorridaDrone.setGeometry(QtCore.QRect(160, 10, 71, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.distanciaRecorridaDrone.sizePolicy().hasHeightForWidth())
        self.distanciaRecorridaDrone.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Uroob")
        font.setPointSize(18)
        self.distanciaRecorridaDrone.setFont(font)
        self.distanciaRecorridaDrone.setStyleSheet("border:none;\n"
"color: rgb(107, 142,35);")
        self.distanciaRecorridaDrone.setAlignment(QtCore.Qt.AlignCenter)
        self.distanciaRecorridaDrone.setObjectName("distanciaRecorridaDrone")
        self.labelDistDrone = QtWidgets.QLabel(self.frame_velocidad_simulacion_2)
        self.labelDistDrone.setGeometry(QtCore.QRect(10, 10, 81, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelDistDrone.sizePolicy().hasHeightForWidth())
        self.labelDistDrone.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Uroob")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.labelDistDrone.setFont(font)
        self.labelDistDrone.setStyleSheet("border:none;\n"
"color: rgb(20, 97, 44);")
        self.labelDistDrone.setAlignment(QtCore.Qt.AlignCenter)
        self.labelDistDrone.setObjectName("labelDistDrone")
        self.verticalLayout_5.addWidget(self.frame_velocidad_simulacion_2)
        self.frame_velocidad_simulacion = QtWidgets.QFrame(self.frame)
        self.frame_velocidad_simulacion.setEnabled(False)
        self.frame_velocidad_simulacion.setMinimumSize(QtCore.QSize(257, 50))
        self.frame_velocidad_simulacion.setMaximumSize(QtCore.QSize(200, 50))
        self.frame_velocidad_simulacion.setStyleSheet("QFrame{\n"
"    border: 5px solid rgb(255, 255, 255);\n"
"    }\n"
"QFrame:hover{\n"
"  border: 5px solid #f9aa33;\n"
"}")
        self.frame_velocidad_simulacion.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_velocidad_simulacion.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_velocidad_simulacion.setObjectName("frame_velocidad_simulacion")
        self.AltitudeDrone = QtWidgets.QLabel(self.frame_velocidad_simulacion)
        self.AltitudeDrone.setGeometry(QtCore.QRect(160, 10, 81, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AltitudeDrone.sizePolicy().hasHeightForWidth())
        self.AltitudeDrone.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Uroob")
        font.setPointSize(18)
        self.AltitudeDrone.setFont(font)
        self.AltitudeDrone.setStyleSheet("border:none;\n"
"color:rgb(107, 142,35);")
        self.AltitudeDrone.setAlignment(QtCore.Qt.AlignCenter)
        self.AltitudeDrone.setObjectName("AltitudeDrone")
        self.labelAlturaDrone = QtWidgets.QLabel(self.frame_velocidad_simulacion)
        self.labelAlturaDrone.setGeometry(QtCore.QRect(20, 10, 61, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelAlturaDrone.sizePolicy().hasHeightForWidth())
        self.labelAlturaDrone.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Uroob")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.labelAlturaDrone.setFont(font)
        self.labelAlturaDrone.setStyleSheet("border:none;\n"
"color: rgb(20, 97, 44);")
        self.labelAlturaDrone.setAlignment(QtCore.Qt.AlignCenter)
        self.labelAlturaDrone.setObjectName("labelAlturaDrone")
        self.verticalLayout_5.addWidget(self.frame_velocidad_simulacion)
        self.horizontalLayout_3.addWidget(self.frame)
        self.verticalLayout_4.addWidget(self.frame_contenido)
        self.barra_titulo = QtWidgets.QFrame(self.datos_teoricos)
        self.barra_titulo.setMinimumSize(QtCore.QSize(0, 0))
        self.barra_titulo.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.barra_titulo.setStyleSheet("background-color: rgb(243, 243, 243);")
        self.barra_titulo.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.barra_titulo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.barra_titulo.setObjectName("barra_titulo")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.barra_titulo)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frame_title = QtWidgets.QFrame(self.barra_titulo)
        self.frame_title.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_title.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_title.setObjectName("frame_title")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_title)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_7 = QtWidgets.QFrame(self.frame_title)
        self.frame_7.setStyleSheet("QFrame{\n"
"    border: 5px solid rgb(255, 255, 255);\n"
"    border-radius: 15px;\n"
"    color: rgb(252, 175, 62);\n"
"}\n"
"QFrame:hover{\n"
"  border: 5px solid #f9aa33;\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Uroob")
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("border:none;\n"
"color: rgb(20, 97, 44);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.radioButtonBCD = QtWidgets.QRadioButton(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButtonBCD.sizePolicy().hasHeightForWidth())
        self.radioButtonBCD.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Uroob")
        font.setPointSize(18)
        self.radioButtonBCD.setFont(font)
        self.radioButtonBCD.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.radioButtonBCD.setStyleSheet("color: rgb(20, 97, 44);")
        self.radioButtonBCD.setChecked(True)
        self.radioButtonBCD.setObjectName("radioButtonBCD")
        self.verticalLayout_3.addWidget(self.radioButtonBCD)
        self.radioButtonSTC = QtWidgets.QRadioButton(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButtonSTC.sizePolicy().hasHeightForWidth())
        self.radioButtonSTC.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Uroob")
        font.setPointSize(18)
        self.radioButtonSTC.setFont(font)
        self.radioButtonSTC.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.radioButtonSTC.setStyleSheet("color: rgb(20, 97, 44);")
        self.radioButtonSTC.setObjectName("radioButtonSTC")
        self.verticalLayout_3.addWidget(self.radioButtonSTC)
        self.radioButtonWave = QtWidgets.QRadioButton(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButtonWave.sizePolicy().hasHeightForWidth())
        self.radioButtonWave.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Uroob")
        font.setPointSize(18)
        self.radioButtonWave.setFont(font)
        self.radioButtonWave.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.radioButtonWave.setStyleSheet("color: rgb(20, 97, 44);\n"
"")
        self.radioButtonWave.setObjectName("radioButtonWave")
        self.verticalLayout_3.addWidget(self.radioButtonWave)
        self.frame_9 = QtWidgets.QFrame(self.frame_7)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.pushButtonSimulacion = QtWidgets.QPushButton(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonSimulacion.sizePolicy().hasHeightForWidth())
        self.pushButtonSimulacion.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Uroob")
        font.setPointSize(18)
        self.pushButtonSimulacion.setFont(font)
        self.pushButtonSimulacion.setStyleSheet("QPushButton{\n"
"    border: 5px solid  rgb(255, 255, 255);\n"
"    border-radius: 15px;\n"
"    color: rgb(20, 97, 44);\n"
"}\n"
"QPushButton:hover{\n"
"  border: 5px solid #ffffff;\n"
"  color: rgb(255, 255, 255);\n"
"}")
        self.pushButtonSimulacion.setObjectName("pushButtonSimulacion")
        self.horizontalLayout_13.addWidget(self.pushButtonSimulacion)
        self.btn_CalcularRuta = QtWidgets.QPushButton(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_CalcularRuta.sizePolicy().hasHeightForWidth())
        self.btn_CalcularRuta.setSizePolicy(sizePolicy)
        self.btn_CalcularRuta.setMinimumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily("Uroob")
        font.setPointSize(18)
        self.btn_CalcularRuta.setFont(font)
        self.btn_CalcularRuta.setStyleSheet("QPushButton{\n"
"    border: 5px solid rgb(255, 255, 255);\n"
"    border-radius: 15px;\n"
"    color: rgb(20, 97, 44);\n"
"}\n"
"QPushButton:hover{\n"
"  border: 5px solid #ffffff;\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.btn_CalcularRuta.setObjectName("btn_CalcularRuta")
        self.horizontalLayout_13.addWidget(self.btn_CalcularRuta)
        self.verticalLayout_3.addWidget(self.frame_9)
        self.horizontalLayout.addWidget(self.frame_7)
        self.horizontalLayout_8.addWidget(self.frame_title)
        self.ParmetrosCPP = QtWidgets.QFrame(self.barra_titulo)
        self.ParmetrosCPP.setStyleSheet("QFrame{\n"
"    border: 5px solid rgb(255, 255, 255);\n"
"    border-radius: 15px;\n"
"    color: rgb(252, 175, 62);\n"
"}\n"
"QFrame:hover{\n"
"  border: 5px solid #f9aa33;\n"
"}")
        self.ParmetrosCPP.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ParmetrosCPP.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ParmetrosCPP.setObjectName("ParmetrosCPP")
        self.frame_13 = QtWidgets.QFrame(self.ParmetrosCPP)
        self.frame_13.setGeometry(QtCore.QRect(20, 140, 251, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_13.sizePolicy().hasHeightForWidth())
        self.frame_13.setSizePolicy(sizePolicy)
        self.frame_13.setStyleSheet("border:none;")
        self.frame_13.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_13)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.sliderAltura = QtWidgets.QSlider(self.frame_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sliderAltura.sizePolicy().hasHeightForWidth())
        self.sliderAltura.setSizePolicy(sizePolicy)
        self.sliderAltura.setStyleSheet("color: #f9aa33;")
        self.sliderAltura.setMaximum(100)
        self.sliderAltura.setOrientation(QtCore.Qt.Horizontal)
        self.sliderAltura.setObjectName("sliderAltura")
        self.horizontalLayout_10.addWidget(self.sliderAltura)
        self.labelAltura = QtWidgets.QLabel(self.frame_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelAltura.sizePolicy().hasHeightForWidth())
        self.labelAltura.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Uroob")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.labelAltura.setFont(font)
        self.labelAltura.setStyleSheet("border:none;\n"
"color: rgb(20, 97, 44);")
        self.labelAltura.setAlignment(QtCore.Qt.AlignCenter)
        self.labelAltura.setObjectName("labelAltura")
        self.horizontalLayout_10.addWidget(self.labelAltura)
        self.AlturaParametro = QtWidgets.QLabel(self.frame_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AlturaParametro.sizePolicy().hasHeightForWidth())
        self.AlturaParametro.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Uroob")
        font.setPointSize(18)
        self.AlturaParametro.setFont(font)
        self.AlturaParametro.setStyleSheet("border:none;\n"
"color: rgb(85, 87, 83);")
        self.AlturaParametro.setAlignment(QtCore.Qt.AlignCenter)
        self.AlturaParametro.setObjectName("AlturaParametro")
        self.horizontalLayout_10.addWidget(self.AlturaParametro)
        self.label_altura_unidades = QtWidgets.QLabel(self.frame_13)
        font = QtGui.QFont()
        font.setFamily("Uroob")
        font.setPointSize(18)
        self.label_altura_unidades.setFont(font)
        self.label_altura_unidades.setStyleSheet("border:none;\n"
"color: rgb(85, 87, 83);")
        self.label_altura_unidades.setAlignment(QtCore.Qt.AlignCenter)
        self.label_altura_unidades.setObjectName("label_altura_unidades")
        self.horizontalLayout_10.addWidget(self.label_altura_unidades)
        self.frame_14 = QtWidgets.QFrame(self.ParmetrosCPP)
        self.frame_14.setGeometry(QtCore.QRect(20, 80, 247, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_14.sizePolicy().hasHeightForWidth())
        self.frame_14.setSizePolicy(sizePolicy)
        self.frame_14.setStyleSheet("border:none;")
        self.frame_14.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.sliderVelocidad = QtWidgets.QSlider(self.frame_14)
        self.sliderVelocidad.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sliderVelocidad.sizePolicy().hasHeightForWidth())
        self.sliderVelocidad.setSizePolicy(sizePolicy)
        self.sliderVelocidad.setStyleSheet("color: #f9aa33;")
        self.sliderVelocidad.setMaximum(100)
        self.sliderVelocidad.setPageStep(5)
        self.sliderVelocidad.setOrientation(QtCore.Qt.Horizontal)
        self.sliderVelocidad.setObjectName("sliderVelocidad")
        self.horizontalLayout_11.addWidget(self.sliderVelocidad)
        self.label_VelocidadDeseada = QtWidgets.QLabel(self.frame_14)
        font = QtGui.QFont()
        font.setFamily("Uroob")
        font.setPointSize(18)
        self.label_VelocidadDeseada.setFont(font)
        self.label_VelocidadDeseada.setStyleSheet("border:none;\n"
"color: rgb(20, 97, 44);")
        self.label_VelocidadDeseada.setAlignment(QtCore.Qt.AlignCenter)
        self.label_VelocidadDeseada.setObjectName("label_VelocidadDeseada")
        self.horizontalLayout_11.addWidget(self.label_VelocidadDeseada)
        self.velocidadParametro = QtWidgets.QLabel(self.frame_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.velocidadParametro.sizePolicy().hasHeightForWidth())
        self.velocidadParametro.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Uroob")
        font.setPointSize(18)
        self.velocidadParametro.setFont(font)
        self.velocidadParametro.setStyleSheet("border:none;\n"
"color: rgb(85, 87, 83);")
        self.velocidadParametro.setAlignment(QtCore.Qt.AlignCenter)
        self.velocidadParametro.setObjectName("velocidadParametro")
        self.horizontalLayout_11.addWidget(self.velocidadParametro)
        self.label_unidades_velocidad = QtWidgets.QLabel(self.frame_14)
        font = QtGui.QFont()
        font.setFamily("Uroob")
        font.setPointSize(18)
        self.label_unidades_velocidad.setFont(font)
        self.label_unidades_velocidad.setStyleSheet("border:none;\n"
"color: rgb(85, 87, 83);")
        self.label_unidades_velocidad.setAlignment(QtCore.Qt.AlignCenter)
        self.label_unidades_velocidad.setObjectName("label_unidades_velocidad")
        self.horizontalLayout_11.addWidget(self.label_unidades_velocidad)
        self.frame_15 = QtWidgets.QFrame(self.ParmetrosCPP)
        self.frame_15.setGeometry(QtCore.QRect(20, 110, 251, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_15.sizePolicy().hasHeightForWidth())
        self.frame_15.setSizePolicy(sizePolicy)
        self.frame_15.setStyleSheet("border:none;")
        self.frame_15.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.sliderAnchoLineas = QtWidgets.QSlider(self.frame_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sliderAnchoLineas.sizePolicy().hasHeightForWidth())
        self.sliderAnchoLineas.setSizePolicy(sizePolicy)
        self.sliderAnchoLineas.setStyleSheet("color: #f9aa33;")
        self.sliderAnchoLineas.setMaximum(20)
        self.sliderAnchoLineas.setOrientation(QtCore.Qt.Horizontal)
        self.sliderAnchoLineas.setObjectName("sliderAnchoLineas")
        self.horizontalLayout_12.addWidget(self.sliderAnchoLineas)
        self.label_ancho = QtWidgets.QLabel(self.frame_15)
        font = QtGui.QFont()
        font.setFamily("Uroob")
        font.setPointSize(18)
        self.label_ancho.setFont(font)
        self.label_ancho.setStyleSheet("border:none;\n"
"color: rgb(20, 97, 44);")
        self.label_ancho.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ancho.setObjectName("label_ancho")
        self.horizontalLayout_12.addWidget(self.label_ancho)
        self.anchoLineasParametro = QtWidgets.QLabel(self.frame_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.anchoLineasParametro.sizePolicy().hasHeightForWidth())
        self.anchoLineasParametro.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Uroob")
        font.setPointSize(18)
        self.anchoLineasParametro.setFont(font)
        self.anchoLineasParametro.setStyleSheet("border:none;\n"
"color: rgb(85, 87, 83);")
        self.anchoLineasParametro.setAlignment(QtCore.Qt.AlignCenter)
        self.anchoLineasParametro.setObjectName("anchoLineasParametro")
        self.horizontalLayout_12.addWidget(self.anchoLineasParametro)
        self.label_unidades_distancia_2 = QtWidgets.QLabel(self.frame_15)
        font = QtGui.QFont()
        font.setFamily("Uroob")
        font.setPointSize(18)
        self.label_unidades_distancia_2.setFont(font)
        self.label_unidades_distancia_2.setStyleSheet("border:none;\n"
"color: rgb(85, 87, 83);")
        self.label_unidades_distancia_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_unidades_distancia_2.setObjectName("label_unidades_distancia_2")
        self.horizontalLayout_12.addWidget(self.label_unidades_distancia_2)
        self.frame_16 = QtWidgets.QFrame(self.ParmetrosCPP)
        self.frame_16.setGeometry(QtCore.QRect(10, 20, 233, 43))
        self.frame_16.setStyleSheet("border:none;")
        self.frame_16.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_16)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_parametros_cpp = QtWidgets.QLabel(self.frame_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_parametros_cpp.sizePolicy().hasHeightForWidth())
        self.label_parametros_cpp.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Uroob")
        font.setPointSize(18)
        self.label_parametros_cpp.setFont(font)
        self.label_parametros_cpp.setStyleSheet("border:none;\n"
"color: rgb(20, 97, 44);")
        self.label_parametros_cpp.setAlignment(QtCore.Qt.AlignCenter)
        self.label_parametros_cpp.setObjectName("label_parametros_cpp")
        self.horizontalLayout_14.addWidget(self.label_parametros_cpp)
        self.horizontalLayout_8.addWidget(self.ParmetrosCPP)
        self.verticalLayout_4.addWidget(self.barra_titulo)
        self.stackedWidget.addWidget(self.datos_teoricos)
        self.datos_simulacion = QtWidgets.QWidget()
        self.datos_simulacion.setObjectName("datos_simulacion")
        self.stackedWidget.addWidget(self.datos_simulacion)
        self.horizontalLayout_2.addWidget(self.stackedWidget)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.verticalLayout.addWidget(self.drop_shadow_frame)
        self.splitter = QtWidgets.QSplitter(self.main_layout)
        self.splitter.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.splitter_2 = QtWidgets.QSplitter(self.main_layout)
        self.splitter_2.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        Coverage.setCentralWidget(self.main_layout)
        self.menubar = QtWidgets.QMenuBar(Coverage)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 670, 22))
        self.menubar.setObjectName("menubar")
        Coverage.setMenuBar(self.menubar)

        self.retranslateUi(Coverage)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Coverage)

    def retranslateUi(self, Coverage):
        _translate = QtCore.QCoreApplication.translate
        Coverage.setWindowTitle(_translate("Coverage", "MainWindow"))
        self.label_title.setText(_translate("Coverage", "CPP Simulation GUI"))
        self.label_Datos_teoricos.setText(_translate("Coverage", "Calculated data"))
        self.label_redundancia.setText(_translate("Coverage", "Redundancy"))
        self.redundancia.setText(_translate("Coverage", " 0"))
        self.label_5.setText(_translate("Coverage", " %"))
        self.lbDistancia.setText(_translate("Coverage", "Distance"))
        self.distanciaTeorica.setText(_translate("Coverage", "0"))
        self.label.setText(_translate("Coverage", " m"))
        self.lbTiempo.setText(_translate("Coverage", "Time"))
        self.tiempoTeorico.setText(_translate("Coverage", "0"))
        self.label_2.setText(_translate("Coverage", " s"))
        self.label_cobertura.setText(_translate("Coverage", "Coverage"))
        self.cobertura.setText(_translate("Coverage", " 0"))
        self.unidadesCobertura.setText(_translate("Coverage", " %"))
        self.label_giros.setText(_translate("Coverage", "Maneuver"))
        self.label_cantidad_giros.setText(_translate("Coverage", "0"))
        self.lbStatus.setText(_translate("Coverage", "On Ground"))
        self.lb_estado.setText(_translate("Coverage", "Status"))
        self.currentWayPoint.setText(_translate("Coverage", "24.3"))
        self.labelWayPOint.setText(_translate("Coverage", "Waypoint"))
        self.velocidadDrone.setText(_translate("Coverage", "24.3"))
        self.labelVeloDrone.setText(_translate("Coverage", "Speed"))
        self.TimeOfFlyDrone.setText(_translate("Coverage", "24.3"))
        self.labelTiempoDrone.setText(_translate("Coverage", "Time"))
        self.distanciaRecorridaDrone.setText(_translate("Coverage", "24.3"))
        self.labelDistDrone.setText(_translate("Coverage", "Distance"))
        self.AltitudeDrone.setText(_translate("Coverage", "24.3"))
        self.labelAlturaDrone.setText(_translate("Coverage", "Height"))
        self.label_3.setText(_translate("Coverage", "Available CPP Algorithms"))
        self.radioButtonBCD.setText(_translate("Coverage", "Boustrophedon_ECD"))
        self.radioButtonSTC.setText(_translate("Coverage", "Spanning Tree_Grid"))
        self.radioButtonWave.setText(_translate("Coverage", "Wavefront_Grid"))
        self.pushButtonSimulacion.setText(_translate("Coverage", "Simulate CPP"))
        self.btn_CalcularRuta.setText(_translate("Coverage", "Compute CPP"))
        self.labelAltura.setText(_translate("Coverage", "Height"))
        self.AlturaParametro.setText(_translate("Coverage", "   0"))
        self.label_altura_unidades.setText(_translate("Coverage", "m"))
        self.label_VelocidadDeseada.setText(_translate("Coverage", "Speed"))
        self.velocidadParametro.setText(_translate("Coverage", " 0"))
        self.label_unidades_velocidad.setText(_translate("Coverage", "m/s"))
        self.label_ancho.setText(_translate("Coverage", "Width"))
        self.anchoLineasParametro.setText(_translate("Coverage", "   0"))
        self.label_unidades_distancia_2.setText(_translate("Coverage", "m"))
        self.label_parametros_cpp.setText(_translate("Coverage", "CPP parameters"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Coverage = QtWidgets.QMainWindow()
    ui = Ui_Coverage()
    ui.setupUi(Coverage)
    Coverage.show()
    sys.exit(app.exec_())
